title: Rohin Garg
description: ML and robotics notes
url: "https://gargrohin.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

plugins:
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title.html

exclude:
  - Gemfile.lock
  - README.md
